apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    field.cattle.io/creatorId: u-6fc5nwq2ou
    field.cattle.io/publicEndpoints: '[{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"desc-tom:ingress-56d5f3c1a8a3f88ebb006b71c4a32cdd","ingressName":"desc-tom:tom-desc-app","hostname":"desc-tom.lbl.gov","allNodes":true},{"addresses":["128.55.206.106"],"port":80,"protocol":"HTTP","serviceName":"desc-tom:ingress-ecfdd332eb86650f33689e51928265af","ingressName":"desc-tom:tom-desc-app","hostname":"tom-desc-app.desc-tom.production.svc.spin.nersc.org","allNodes":true}]'
    nersc.gov/collab_uids: "70268"
    nersc.gov/gid: "95089"
    nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,92576,95089,96414
    nersc.gov/roles: user
    nersc.gov/uid: "95089"
    nersc.gov/username: raknop
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-desc-tom-tom-desc-app
  name: tom-desc-app
  selfLink: /apis/apps/v1/namespaces/desc-tom/deployments/tom-desc-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-tom-desc-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-07-06T20:36:39Z"
        field.cattle.io/publicEndpoints: '[{"addresses":["128.55.206.106"],"allNodes":true,"hostname":"desc-tom.lbl.gov","ingressId":"desc-tom:tom-desc-app","port":80,"protocol":"HTTP","serviceId":"desc-tom:ingress-56d5f3c1a8a3f88ebb006b71c4a32cdd"},{"addresses":["128.55.206.106"],"allNodes":true,"hostname":"tom-desc-app.desc-tom.production.svc.spin.nersc.org","ingressId":"desc-tom:tom-desc-app","port":80,"protocol":"HTTP","serviceId":"desc-tom:ingress-ecfdd332eb86650f33689e51928265af"}]'
        nersc.gov/collab_uids: "70268"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,92576,95089,96414
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-tom-desc-app
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: tom-desc-postgres
        - name: DB_NAME
          value: tom_desc
        - name: DB_PASS
          value: fragile
        - name: DB_USER
          value: postgres
        - name: FINK_GROUP_ID
          value: lsstfr-johann
        - name: FINK_SERVER
          value: 134.158.74.95:24499,
        - name: FINK_TOPIC
          value: fink_early_sn_candidates_ztf
        - name: FINK_USERNAME
          value: johann
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/GCP_auth_key-pitt_broker_user_project.json
        - name: GOOGLE_CLOUD_PROJECT
          value: pitt-broker-user-project
        image: registry.services.nersc.gov/raknop/tom-desc-production
        imagePullPolicy: Always
        name: tom-desc-app
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: tom-desc-app-secrets
        - mountPath: /tom_desc
          name: tom-desc-production-deployment
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 60152
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tom-desc-app-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: desc-tom-secrets
      - hostPath:
          path: /global/cfs/cdirs/m1727/tom/deploy_production/tom_desc
          type: Directory
        name: tom-desc-production-deployment
status: {}
