apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    field.cattle.io/creatorId: u-6fc5nwq2ou
    nersc.gov/collab_uids: "70268"
    nersc.gov/gid: "95089"
    nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,92576,95089,96414
    nersc.gov/roles: user
    nersc.gov/uid: "95089"
    nersc.gov/username: raknop
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-desc-tom-tom-desc-postgres
  name: tom-desc-postgres
  selfLink: /apis/apps/v1/namespaces/desc-tom/deployments/tom-desc-postgres
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desc-tom-tom-desc-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2022-07-06T19:46:04Z"
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "70268"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 45703,60152,57177,58102,59318,60070,63477,64483,79186,70268,92576,95089,96414
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-desc-tom-tom-desc-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: tom_desc
        - name: POSTGRES_PASSWORD_FILE
          value: /secrets/postgres_password
        - name: POSTGRES_USER
          value: postgres
        image: registry.services.nersc.gov/raknop/tom-desc-postgres
        imagePullPolicy: Always
        name: tom-desc-postgres
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: vol2
        - mountPath: /var/lib/postgresql/data
          name: tom-desc-postgres
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol2
        secret:
          defaultMode: 256
          optional: false
          secretName: desc-tom-secrets
      - name: tom-desc-postgres
        persistentVolumeClaim:
          claimName: tom-desc-postgres
status: {}
